version: '3'
services:
  backend:
    build:
      context: ./backend
      # dockerfile: dockerfile
    ports:
      - '8000:8000'
    volumes:
      - /app/node_modules
      - /backend:/app
  frontend:
    build:
      context: ./frontend
      # dockerfile: dockerfile
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules
      - /frontend:/app
  nginx:
    image: imageName
  mongodb:
    image: imageName
  redis:
    image: imageName
